version: '3.8'
services:
  zabbix-proxy:
    image: nagixti/zabbix-proxy:v1.0
    env_file:
      - .env 
    environment:
      - ZBX_SERVER_PORT=10051
      - ZBX_LOGTYPE=file
      - ZBX_LOGFILE=/var/log/zabbix/zabbix_proxy.log
      - ZBX_LOGFILESIZE=0
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_PROXYOFFLINEBUFFER=24
      - ZBX_PROXYBUFFERMODE=hybrid
      - ZBX_PROXYMEMORYBUFFERSIZE=64M
      - ZBX_PROXYMEMORYBUFFERAGE=600
      - ZBX_PROXYCONFIGFREQUENCY=60
      - ZBX_STARTAGENTPOLLERS=15
      - ZBX_STARTHTTPAGENTPOLLERS=1
      - ZBX_STARTSNMPPOLLERS=15
      - ZBX_STARTPOLLERSUNREACHABLE=15
      - ZBX_STARTTRAPPERS=10
      - ZBX_STARTPINGERS=15
      - ZBX_STARTDISCOVERERS=10
      - ZBX_STARTHTTPPOLLERS=1
      - ZBX_STARTVMWARECOLLECTORS=2
      - ZBX_VMWARECACHESIZE=32M
      - ZBX_ENABLE_SNMP_TRAPS=false
      - ZBX_CACHESIZE=64M
      - ZBX_HISTORYCACHESIZE=64M
      - ZBX_TIMEOUT=30
      - ZBX_ALLOWROOT=0
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /home/marcelo/Docker/zabbix-key.psk:/etc/zabbix/.zabbix-key.psk:ro
       - zabbix-proxy-logs:/var/log/zabbix
       - zabbix-proxy-data:/var/lib/zabbix
    network_mode: host
volumes:
  zabbix-proxy-data:
  zabbix-proxy-logs:
